#开发环境
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://168.61.9.38:3306/ruoyi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: cloudmp
    password: cloudmmp
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    password:    # 密码（默认为空）
    cluster:
      nodes:
        - 168.61.2.20:6379
    timeout: 3000
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接      
        min-idle: 5       # 连接池中的最小空闲连接


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.htsc.htcloud.flea.entity

# 日志配置
logging:
  config: classpath:log4j2.xml

# ALM配置
alm:
  url: http://168.61.11.216:9000/ALM/htpm/CommonAPI

# RIS以及代理配置
ris:
  url: https://168.16.3.67
  username: admin
  password: shterm
  dev:
    win:
      name: appadmin
      password: Htsc&app@0123465
  proxy:
    flag: true
    host: 168.61.18.139
    port: 3128


#线程池配置
async:
  # 配置核心线程数
  corePoolSize: 10
  # 配置最大线程数
  maxPoolSize: 30
  # 配置队列大小
  queueCapacity: 9999
  # 配置线程池中的线程的名称前缀
  namePrefix: async-flea-